name = "CYAxiverse"
uuid = "e5e45d93-5055-4eab-878b-2e484be3f951"
authors = ["Viraf M. Mehta"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
